name: RSS Retrieve and Send Email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 5"

jobs:
  pages-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.5.10' 
        cache: 'pip' # caching pip dependencies
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
        RECIPIENT_EMAIL_ADDRESS: ${{ secrets.RECIPIENT_EMAIL_ADDRESS }}
    - run: pip install -r requirements.txt
    - run: python rss.py
