name: Auto pages deploy

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '3 */2 * * *'
